### PR TITLE
Error formatting not using fmt.Errorf

### PR DESCRIPTION
**Pull request by sejin-P**
1.  In [golang wiki](https://github.com/golang/go/wiki/CodeReviewComments#error-strings), the document recommends to not use capitalization in error string except some edge cases.
2.  Don't need to assign error value with string messages using `%v`, `+` is simpler.
3.  fmt.Errorf always need more calculation than assigning error value with errors.New
4.  github.com/pkg/errors provide simple error handlings.

### CODE REVIEW

**Comment by beltran** [comment]
Thank you for your contribution

**Comment by sejin-P** [comment]
I forgot to fix test codes, I'm gonna fix them tonight

**Comment by beltran** [comment]
No worries, they are fixed after the latest commit. I'm worried however about this because some users may be reading the errors (like the test that was failing) and this may break their code.

**Comment by sejin-P** [comment]
Then how about using error message same as before?

**Comment by sejin-P** [comment]
I fixed some error messages same as before

**Comment by sejin-P** [comment]
@beltran Do you have any additional opinions for this pr?

**Comment by beltran** [comment]
Nope, thank you for contributing

**Pull request merged**
